#!/usr/bin/env python3

import getopt
import sys

from mtda_mqtt.main import MTDAMqtt

class A:
    def main(self):
        config = None
        daemonize = False
        detach = True 
        options,stuff = getopt.getopt(sys.argv[1:], 'c:dhnr:v', ['daemon','help', 'no-detach', 'remote=', 'version'])
        print(type(options),type(stuff))
        print(options)
        for opt, arg in options:
            if opt in ('-c', '--config'):
                config = arg
            if opt in ('-d', '--daemon'):
                daemonize = True
            if opt in ('-h', '--help'):
                sys.exit(0)
            if opt in ('-r', '--remote'):
                self.remote = arg
                print(self.remote)
            if opt in ('-v', '--version'):
                sys.exit(0)
        print(stuff)


if __name__ == '__main__':
    obj=A()
    obj.main()
